model_reasoning_effort = "low"
personality = "pragmatic"
forced_login_method = "chatgpt"
model = "gpt-5.5"
web_search = "live"
notify = [ "$HOME/.codex/hooks/notify-terminal-notifier.sh" ]
suppress_unstable_features_warning = true
plan_mode_reasoning_effort = "medium"
approval_policy = "on-request"
sandbox_mode = "workspace-write"

[features]
shell_snapshot = true
multi_agent_v2 = true
prevent_idle_sleep = true
js_repl = true
hooks = true
undo = true
tool_search = true
memories = false
chronicle = false

[feedback]
enabled = false

[sandbox_workspace_write]
network_access = true

[tui]
status_line = [ "model-with-reasoning", "project-name", "git-branch", "context-used", "five-hour-limit", "weekly-limit", "codex-version", "pull-request-number", "branch-changes", "run-state", "fast-mode", "thread-title", "task-progress" ]
theme = "catppuccin-latte"
status_line_use_colors = true

[tui.model_availability_nux]
"gpt-5.5" = 4

[projects."/Users/nasuno.ayumu/dev/github.com/luvpame/dotfiles"]
trust_level = "trusted"

[projects."/Users/nasuno.ayumu/dev/github.com/luvpame/calpeek"]
trust_level = "trusted"

[projects."/Users/nasuno.ayumu/Documents/Codex/2026-05-14/superpowers-brainstorming-users-nasuno-ayumu-codex"]
trust_level = "trusted"

[projects."/Users/nasuno.ayumu/dev/github.com/luvpame/notion-enhancer"]
trust_level = "trusted"

[projects."/Users/nasuno.ayumu/Documents/Codex/2026-05-18/superpowers-brainstorming-users-nasuno-ayumu-codex"]
trust_level = "trusted"

[projects."/Users/nasuno.ayumu/dev/github.com/luvpame/github-enhancer"]
trust_level = "trusted"

[projects."/Users/nasuno.ayumu/Documents/Codex/2026-05-18/browser-extension-template-ghq-get-ci"]
trust_level = "trusted"

[projects."/Users/nasuno.ayumu/dev/github.com/luvpame/browser-extension-template"]
trust_level = "trusted"

[marketplaces.openai-bundled]
last_updated = "2026-05-18T23:44:05Z"
source_type = "local"
source = "/Users/nasuno.ayumu/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-05-19T00:19:26Z"
source_type = "local"
source = "/Users/nasuno.ayumu/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[plugins."superpowers@openai-curated"]
enabled = true

[plugins."codex-security@openai-curated"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[plugins."chrome@openai-bundled"]
enabled = true

[hooks.state."/Users/nasuno.ayumu/.codex/hooks.json:pre_tool_use:0:0"]
trusted_hash = "sha256:fbce185f06778f6935e18e60df59bbaeb3ba05d558ba9dfbe64b8133f5ce68fb"

[hooks.state."/Users/nasuno.ayumu/.codex/hooks.json:pre_tool_use:0:1"]
trusted_hash = "sha256:834b651aa08dfd2df53a7236deeea5833d288e73624e6265cff78ea1dd38d3fd"

[hooks.state."/Users/nasuno.ayumu/.codex/hooks.json:session_start:0:0"]
trusted_hash = "sha256:5d1ae6f116fa0b65e1e69653956185b504f1a0fc00b7d6c3f26bce68f17eff2f"

[hooks.state."/Users/nasuno.ayumu/.codex/hooks.json:stop:0:0"]
trusted_hash = "sha256:3988b809d1a46c97a9c5405712be87db63906a51f9467c7ca88ce36b60b649a5"

[hooks.state."/Users/nasuno.ayumu/.codex/hooks.json:user_prompt_submit:0:0"]
trusted_hash = "sha256:f80728ad206e6647577d90719509022f480a805fe1872bc844eefe51fa36fe13"
