version = 1

# 一括 add を禁止する
[[rules]]
matcher = "Bash"
regex = '\bgit\s+add\s+(-A|--all|\.($|[ ;|&]))'
message = "すべてのファイルを一括で git-add しないでください。追加するファイルを個別に指定してください。"

# アクセス禁止するファイル
# 'File'は'Read|Write|Edit'のエイリアス
[[rules]]
matcher = "File"
regex = '\.env$'
message = ".envファイルへのアクセスは禁止されています。必要な値はユーザーに直接入力を求めてください。"
