#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4
TOTAL_MINUTES=10

KEY_LABEL="git-sign"
KEY_TYPE="p-256-ne"
KEY_PROTECTION="none"
SSH_DIR="${HOME}/.ssh"
KEY_PATH="${SSH_DIR}/id_git_sign"
PUBLIC_KEY_PATH="${KEY_PATH}.pub"
SSH_SK_PROVIDER_PATH="/usr/lib/ssh-keychain.dylib"
SSH_ASKPASS_PATH="/usr/bin/true"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd -P)"
SIGNER_PATH="${REPO_ROOT}/config/git/ssh-sign"

HOSTNAME_SHORT="$(hostname -s 2>/dev/null || true)"
if [[ "$HOSTNAME_SHORT" =~ ^[[:alnum:]][[:alnum:]._-]*$ ]]; then
  GITHUB_TITLE="git-sign@${HOSTNAME_SHORT}"
else
  GITHUB_TITLE="git-sign"
fi

REGISTER_GITHUB=false
SC_AUTH=""
GIT_USER_NAME=""
GIT_USER_EMAIL=""
CTK_STATE=""
CTK_LABEL_ROWS=""
CTK_LABEL_COUNT=0
CTK_IDENTITY_COUNT=0
CTK_UNEXPECTED_COUNT=0
NEEDS_KEY_CREATION=false
GENERATED_PRIVATE=""
GENERATED_PUBLIC=""
TEMP_DIR=""
TEMP_DIRS=()

usage() {
  printf 'Usage: %s [--register-github]\n' "${0##*/}" >&2
}

abort() {
  warn "$1"
  printf '%sSetup stopped without deleting or overwriting existing keys.%s\n' "$RED" "$RESET" >&2
  exit 1
}

path_exists() {
  [[ -e "$1" || -L "$1" ]]
}

cleanup() {
  local dir
  set +e
  for dir in "${TEMP_DIRS[@]}"; do
    [[ -d "$dir" ]] && rm -rf "$dir"
  done
}

trap cleanup EXIT

parse_options() {
  while (( $# > 0 )); do
    case "$1" in
      --register-github)
        REGISTER_GITHUB=true
        ;;
      *)
        usage
        exit 2
        ;;
    esac
    shift
  done
}

refresh_ctk_state() {
  local state
  if ! state="$("$SC_AUTH" list-ctk-identities -t ssh 2>/dev/null)"; then
    return 1
  fi
  CTK_STATE="$state"
  CTK_LABEL_ROWS="$(printf '%s\n' "$CTK_STATE" | awk -v label="$KEY_LABEL" '
    {
      for (i = 1; i <= NF; i++) {
        if ($i == label) {
          print
          next
        }
      }
    }')"
  CTK_LABEL_COUNT="$(printf '%s\n' "$CTK_LABEL_ROWS" | awk 'NF { count++ } END { print count + 0 }')"
  CTK_IDENTITY_COUNT="$(printf '%s\n' "$CTK_STATE" | awk '
    $1 ~ /^p-(256|384|521)(-ne)?$/ { count++ }
    END { print count + 0 }')"
  CTK_UNEXPECTED_COUNT="$(printf '%s\n' "$CTK_STATE" | awk '
    NF == 0 { next }
    $1 == "Key" && $2 == "Type" { next }
    $1 ~ /^p-(256|384|521)(-ne)?$/ { next }
    /^-+$/ { next }
    { count++ }
    END { print count + 0 }')"
}

ssh_keygen_with_provider() {
  SSH_SK_PROVIDER="$SSH_SK_PROVIDER_PATH" \
    SSH_ASKPASS_REQUIRE=force \
    SSH_ASKPASS="$SSH_ASKPASS_PATH" \
    /usr/bin/ssh-keygen "$@"
}

public_key_line() {
  local path="$1" line
  [[ -f "$path" && ! -L "$path" && -r "$path" ]] || return 1
  if ! /usr/bin/ssh-keygen -E sha256 -lf "$path" >/dev/null 2>&1; then
    return 1
  fi
  if ! line="$(awk '
    NF >= 2 && $1 !~ /^#/ {
      print $1 " " $2
      count++
    }
    END {
      if (count != 1) exit 1
    }' "$path")"; then
    return 1
  fi
  printf '%s\n' "$line"
}

private_public_key_line() {
  local path="$1" line
  if ! line="$(ssh_keygen_with_provider -y -P "" -f "$path" 2>/dev/null)"; then
    return 1
  fi
  if ! line="$(printf '%s\n' "$line" | awk 'NF >= 2 { print $1 " " $2; exit }')"; then
    return 1
  fi
  [[ -n "$line" ]] || return 1
  printf '%s\n' "$line"
}

validate_key_pair() {
  local private_path="$1" public_path="$2"
  local public_line private_line
  public_line="$(public_key_line "$public_path")" || return 1
  private_line="$(private_public_key_line "$private_path")" || return 1
  [[ "$public_line" == "$private_line" ]]
}

public_key_fingerprint() {
  local path="$1" output fingerprint
  if ! output="$(/usr/bin/ssh-keygen -E sha256 -lf "$path" 2>/dev/null)"; then
    return 1
  fi
  fingerprint="$(printf '%s\n' "$output" | awk 'NR == 1 { print $2 }')"
  [[ -n "$fingerprint" ]] || return 1
  printf '%s\n' "$fingerprint"
}

validate_ctk_identity() {
  local expected_fingerprint="$1"
  local row key_type key_hash protection label rest
  [[ "$CTK_LABEL_COUNT" -eq 1 ]] || return 1
  row="$CTK_LABEL_ROWS"
  read -r key_type key_hash protection label rest <<< "$row"
  [[ "$key_type" == "$KEY_TYPE" ]] || return 1
  [[ "$key_hash" == "$expected_fingerprint" ]] || return 1
  [[ "$protection" == "$KEY_PROTECTION" ]] || return 1
  [[ "$label" == "$KEY_LABEL" ]] || return 1
  return 0
}

make_temp_dir() {
  local dir
  if ! dir="$(mktemp -d "${TMPDIR:-/tmp}/git-signing.XXXXXX")"; then
    return 1
  fi
  TEMP_DIRS+=("$dir")
  if ! chmod 700 "$dir"; then
    return 1
  fi
  TEMP_DIR="$dir"
}

find_generated_pair() {
  local path
  local private_count=0
  local public_count=0
  GENERATED_PRIVATE=""
  GENERATED_PUBLIC=""

  for path in "$TEMP_DIR"/*; do
    [[ -e "$path" || -L "$path" ]] || continue
    [[ -f "$path" && ! -L "$path" ]] || return 1
    case "$path" in
      *.pub)
        public_count=$((public_count + 1))
        GENERATED_PUBLIC="$path"
        ;;
      *)
        private_count=$((private_count + 1))
        GENERATED_PRIVATE="$path"
        ;;
    esac
  done

  [[ "$private_count" -eq 1 && "$public_count" -eq 1 ]] || return 1
  [[ "${GENERATED_PRIVATE}.pub" == "$GENERATED_PUBLIC" ]]
}

move_generated_pair() {
  path_exists "$KEY_PATH" && return 1
  path_exists "$PUBLIC_KEY_PATH" && return 1

  chmod 600 "$GENERATED_PRIVATE" || return 1
  chmod 644 "$GENERATED_PUBLIC" || return 1

  mv -n "$GENERATED_PRIVATE" "$KEY_PATH" || return 1
  path_exists "$GENERATED_PRIVATE" && return 1
  path_exists "$PUBLIC_KEY_PATH" && return 1

  mv -n "$GENERATED_PUBLIC" "$PUBLIC_KEY_PATH" || return 1
  path_exists "$GENERATED_PUBLIC" && return 1
}

print_registration_command() {
  printf '  gh ssh-key add %q --title %q --type signing\n' "$PUBLIC_KEY_PATH" "$GITHUB_TITLE"
}

github_signing_key_present() {
  local expected keys key normalized
  expected="$(public_key_line "$PUBLIC_KEY_PATH")" || return 2
  if ! keys="$(gh api user/ssh_signing_keys --paginate --jq '.[].key' 2>/dev/null)"; then
    return 2
  fi
  while IFS= read -r key; do
    [[ -n "$key" ]] || continue
    normalized="$(printf '%s\n' "$key" | awk 'NF >= 2 { print $1 " " $2; exit }')"
    [[ "$normalized" == "$expected" ]] && return 0
  done <<< "$keys"
  return 1
}

check_github_signing_key_access() {
  local error_file
  make_temp_dir || return 3
  error_file="${TEMP_DIR}/github-api-error"
  if gh api user/ssh_signing_keys --paginate --jq '.[].key' >/dev/null 2>"$error_file"; then
    return 0
  fi
  if grep -Fq 'admin:ssh_signing_key' "$error_file"; then
    return 2
  fi
  return 1
}

register_github_key() {
  local status
  print_registration_command
  if [[ "$REGISTER_GITHUB" != true ]]; then
    note "--register-github を指定しなかったため、GitHubは変更していません。"
    return
  fi

  if github_signing_key_present; then
    note "この公開鍵はGitHubのSigning keysに登録済みです。"
    return
  else
    status=$?
    [[ "$status" -eq 1 ]] || abort "GitHubのSigning keysを再確認できませんでした。事前診断後にAPI応答が変わったため、登録せず停止します。"
  fi

  if ! confirm "この公開鍵をGitHubのSigning keysへ登録しますか？"; then
    abort "GitHubへの登録をキャンセルしました。"
  fi

  if gh ssh-key add "$PUBLIC_KEY_PATH" --title "$GITHUB_TITLE" --type signing >/dev/null 2>&1; then
    note "GitHubのSigning keysへ登録しました。"
    return
  fi

  if github_signing_key_present; then
    note "この公開鍵はGitHubのSigning keysに登録済みです。"
    return
  else
    status=$?
  fi
  [[ "$status" -eq 1 ]] || abort "GitHubのSigning keysを再確認できませんでした。登録結果を判定できないため停止します。"
  abort "GitHubへの公開鍵登録に失敗しました。"
}

self_test() {
  local allowed_signers public_line public_type public_blob
  make_temp_dir || abort "一時ディレクトリを作成できませんでした。"
  allowed_signers="${TEMP_DIR}/allowed_signers"
  public_line="$(public_key_line "$PUBLIC_KEY_PATH")" || abort "公開鍵を読み取れません。"
  read -r public_type public_blob <<< "$public_line"
  printf '%s namespaces="git" %s %s\n' \
    "$GIT_USER_EMAIL" "$public_type" "$public_blob" > "$allowed_signers"
  chmod 600 "$allowed_signers" || abort "一時allowed_signersの権限を設定できませんでした。"

  if ! git -C "$TEMP_DIR" init -q; then
    abort "一時Git repositoryを初期化できませんでした。"
  fi
  if ! git -C "$TEMP_DIR" \
    -c "user.name=$GIT_USER_NAME" \
    -c "user.email=$GIT_USER_EMAIL" \
    -c gpg.format=ssh \
    -c "user.signingkey=$KEY_PATH" \
    -c commit.gpgsign=true \
    -c "gpg.ssh.program=$SIGNER_PATH" \
    commit --allow-empty -m "Secure Enclave signing self-test" >/dev/null 2>&1; then
    abort "Secure Enclave鍵で署名commitを作成できませんでした。"
  fi
  if ! git -C "$TEMP_DIR" \
    -c gpg.format=ssh \
    -c "gpg.ssh.program=$SIGNER_PATH" \
    -c "gpg.ssh.allowedSignersFile=$allowed_signers" \
    verify-commit HEAD >/dev/null 2>&1; then
    abort "一時署名commitの検証に失敗しました。"
  fi
  note "一時repositoryで署名とgit verify-commitが成功しました。"
}

parse_options "$@"

banner "Git commit signing setup"

stage "事前診断" 2
say "macOS、Secure Enclave、既存設定を確認します。"
[[ "$(uname -s)" == "Darwin" ]] || abort "このwizardはmacOSでのみ実行できます。"
SC_AUTH="$(command -v sc_auth || true)"
[[ -x "$SC_AUTH" ]] || abort "sc_auth が見つかりません。"
[[ -x /usr/bin/ssh-keygen ]] || abort "/usr/bin/ssh-keygen が見つかりません。"
[[ -f "$SSH_SK_PROVIDER_PATH" && -r "$SSH_SK_PROVIDER_PATH" ]] || abort "Secure Enclave用providerが見つかりません。"
[[ -x "$SSH_ASKPASS_PATH" ]] || abort "/usr/bin/true が見つかりません。"
[[ -x "$SIGNER_PATH" ]] || abort "署名ラッパーが実行可能ではありません: $SIGNER_PATH"
command -v git >/dev/null 2>&1 || abort "git が見つかりません。"

if path_exists "$SSH_DIR"; then
  [[ -d "$SSH_DIR" && ! -L "$SSH_DIR" ]] || abort "$HOME/.ssh がディレクトリではありません。"
else
  mkdir -p "$SSH_DIR" || abort "$HOME/.ssh を作成できませんでした。"
fi
chmod 700 "$SSH_DIR" || abort "$HOME/.sshの権限を設定できませんでした。"

GIT_USER_NAME="$(git config --get user.name 2>/dev/null || true)"
GIT_USER_EMAIL="$(git config --get user.email 2>/dev/null || true)"
[[ -n "$GIT_USER_NAME" ]] || abort "Gitのuser.nameが設定されていません。"
[[ -n "$GIT_USER_EMAIL" ]] || abort "Gitのuser.emailが設定されていません。"

if [[ "$REGISTER_GITHUB" == true ]]; then
  command -v gh >/dev/null 2>&1 || abort "--register-githubにはghが必要です。"
  gh auth status >/dev/null 2>&1 || abort "--register-githubには認証済みのghが必要です。"
  if check_github_signing_key_access; then
    :
  else
    github_api_status=$?
    case "$github_api_status" in
      2)
        printf '  gh auth refresh -h github.com -s admin:ssh_signing_key\n'
        abort "GitHubのSigning keys APIに必要なscopeがありません。上のコマンドを実行してから再実行してください。"
        ;;
      1)
        abort "GitHubのSigning keys APIへアクセスできません。scope不足とは断定せず停止します。"
        ;;
      *)
        abort "GitHub APIの事前確認用一時ディレクトリを作成できませんでした。"
        ;;
    esac
  fi
fi

if ! refresh_ctk_state; then
  abort "CryptoTokenKitの状態を取得できません。通常のTerminalから再実行してください。"
fi
[[ "$CTK_UNEXPECTED_COUNT" -eq 0 ]] || abort "CryptoTokenKitの状態を解釈できません。自動修復せず停止します。"

PRIVATE_PRESENT=false
PUBLIC_PRESENT=false
path_exists "$KEY_PATH" && PRIVATE_PRESENT=true
path_exists "$PUBLIC_KEY_PATH" && PUBLIC_PRESENT=true
if [[ "$PRIVATE_PRESENT" != "$PUBLIC_PRESENT" ]]; then
  abort "鍵ファイルが片方だけ存在します。削除や再生成はせず、状態を確認してください。"
fi

if [[ "$PRIVATE_PRESENT" == false ]]; then
  [[ "$CTK_IDENTITY_COUNT" -eq 0 ]] || abort "鍵ファイルがないのにCTK identityが存在します。自動修復せず停止します。"
  NEEDS_KEY_CREATION=true
else
  [[ "$CTK_LABEL_COUNT" -eq 1 ]] || abort "git-signのCTK identityを一意に特定できません。自動修復せず停止します。"
fi

stage "Secure Enclave鍵" 3
note "OpenSSHの汎用PINプロンプトはwizardが空入力で処理します。"
note "PINやパスワードを求められたら、何も入力せず中断してください。"
if [[ "$NEEDS_KEY_CREATION" == true ]]; then
  step "Secure Enclave内にp-256-ne、保護なしのCTK identityを作成します。"
  if ! "$SC_AUTH" create-ctk-identity -l "$KEY_LABEL" -k "$KEY_TYPE" -t "$KEY_PROTECTION"; then
    abort "Secure Enclave identityの作成に失敗しました。"
  fi
  refresh_ctk_state || abort "作成後のCTK状態を取得できません。"
  [[ "$CTK_UNEXPECTED_COUNT" -eq 0 ]] || abort "作成後のCTK状態を解釈できません。"
  [[ "$CTK_IDENTITY_COUNT" -eq 1 ]] || abort "作成後のCTK identityが一意ではありません。"
  [[ "$CTK_LABEL_COUNT" -eq 1 ]] || abort "作成後のgit-sign CTK identityが一意ではありません。"

  make_temp_dir || abort "鍵ファイル用の一時ディレクトリを作成できませんでした。"
  step "一時ディレクトリでSecure EnclaveのSSH参照ファイルを取得します。"
  if ! (
    cd "$TEMP_DIR"
    ssh_keygen_with_provider -w "$SSH_SK_PROVIDER_PATH" -K -N ""
  ); then
    abort "Secure EnclaveのSSH参照ファイル取得に失敗しました。"
  fi
  find_generated_pair || abort "生成されたSSH鍵ファイルの組を一意に特定できません。"
  validate_key_pair "$GENERATED_PRIVATE" "$GENERATED_PUBLIC" || abort "生成された公開鍵と参照ファイルが一致しません。"
  generated_fingerprint="$(public_key_fingerprint "$GENERATED_PUBLIC")" || abort "生成された公開鍵の指紋を取得できません。"
  validate_ctk_identity "$generated_fingerprint" || abort "生成された鍵とCTK identityが一致しません。"
  move_generated_pair || abort "既存ファイルを上書きせずに鍵を配置できませんでした。"
else
  step "既存の鍵ファイルとCTK identityを検証します。"
  [[ -f "$KEY_PATH" && -f "$PUBLIC_KEY_PATH" ]] || abort "鍵ファイルを参照できません。"
  [[ ! -L "$KEY_PATH" && ! -L "$PUBLIC_KEY_PATH" ]] || abort "鍵ファイルはシンボリックリンクでは扱いません。"
  validate_key_pair "$KEY_PATH" "$PUBLIC_KEY_PATH" || abort "既存の公開鍵と参照ファイルが一致しません。"
  existing_fingerprint="$(public_key_fingerprint "$PUBLIC_KEY_PATH")" || abort "既存公開鍵の指紋を取得できません。"
  validate_ctk_identity "$existing_fingerprint" || abort "既存の鍵とCTK identityが一致しません。"
  chmod 600 "$KEY_PATH" || abort "秘密鍵参照ファイルの権限を設定できませんでした。"
  chmod 644 "$PUBLIC_KEY_PATH" || abort "公開鍵の権限を設定できませんでした。"
fi
note "Git設定はまだ1Password署名のままです。GitHubのVerified確認後に切り替えます。"

stage "署名セルフテスト" 3
say "一時repositoryだけを使い、現在のグローバル署名設定を上書きして検証します。"
self_test

stage "GitHub Signing key" 2
say "署名セルフテストの成功後に公開鍵をGitHubのSigning keysへ登録します。"
register_github_key

finish
