# Lazygit の画面設定
gui:
  tabWidth: 2

  # 次のいずれか: 'auto'（既定） | 'en' | 'zh-CN' | 'zh-TW' | 'pl' | 'nl' | 'ja' | 'ko'
  # | 'ru' | 'pt'
  language: ja

  # 使用する Nerd Fonts バージョン
  # 次のいずれか: '2' | '3' | 空文字列（既定）
  # 空の場合、アイコンを表示しない。
  nerdFontsVersion: "3"

# git に関する設定
git:
  # ページャー設定の配列。各要素は次の形式:
  #
  #   # git diff コマンドの --color 引数の値。一部のページャーは
  #   # 'always' を必要とし、別のページャーは 'never' を必要とする
  #   colorArg: "always"
  #
  #   # 例:
  #   # diff-so-fancy
  #   # ydiff -p cat -s --wrap --width={{columnWidth}}
  #   pager: ""
  #
  #   # 例: 'difft --color=always'
  #   externalDiffCommand: ""
  #
  #   # true の場合、ページングに git の `diff.external` 設定を使用する。
  #   # `externalDiffCommand` と比べた利点は、
  #   # .gitattributes でファイル種別ごとに設定できる点。参照:
  #   # https://git-scm.com/docs/gitattributes#_defining_an_external_diff_driver.
  #   useExternalDiffGitConfig: false
  #
  # 参照: https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Pagers.md
  # 詳細は上記を参照。
  pagers:
    - pager: hunk pager

  # true の場合、コミットメッセージ内の絵文字文字列を解釈（例: :rocket: -> 🚀）
  # （本来は 'git' ではなく 'gui' 配下にあるべき設定）
  parseEmoji: true
